"""
A dictionary of spanish - english translations
which are deemed to be at an easy level of difficulty"""
easy_words = [
    {"como": "as"},
    {"su": "his"},
    {"que": "that/which/than"},
    {"él": "he"},
    {"era": "was/he was/she was"},
    {"para": "for"},
    {"en": "on/in"},
    {"son": "they are"},
    {"con": "with"},
    {"ellos": "they"},
    {"ser": "to be"},
    {"en": "at"},
    {"uno": "one"},
    {"tener": "to have"},
    {"este": "this"},
    {"desde": "from/since"},
    {"por": "by"},
    {"caliente": "hot"},
    {"palabra": "word"},
    {"pero": "but"},
    {"qué": "what/which/that/whom/whose/how"},
    {"algunos": "some"},
    {"es": "is/it is"},
    {"usted": "you"},
    {"o": "or"},
    {"tenido": "had"},
    {"la": "the"},
    {"de": "of/from/about"},
    {"a": "to"},
    {"y": "and"},
    {"un": "a"},
    {"en": "in"},
    {"nos": "we"},
    {"lata": "can"},
    {"fuera": "out"},
    {"otros": "others"},
    {"eran": "they were"},
    {"hacer": "to do/to make"},
    {"su": "their/his/her"},
    {"tiempo": "time"},
    {"si": "if/yes"},
    {"lo hará": "will/it will"},
    {"cómo": "how"},
    {"dicho": "said"},
    {"un": "an/a"},
    {"cada": "each/every"},
    {"decir": "to tell/to say"},
    {"hace": "does/he does/she does"},
    {"conjunto": "set"},
    {"tres": "three"},
    {"querer": "to want"},
    {"aire": "air"},
    {"así": "well/like this/like that"},
    {"también": "also"},
    {"jugar": "to play"},
    {"pequeño": "small"},
    {"fin": "end"},
    {"poner": "to put"},
    {"leer": "to read"},
    {"mano": "hand"},
    {"puerto": "port"},
    {"grande": "large"},
    {"deletrear": "to spell"},
    {"añadir": "to add"},
    {"incluso": "even"},
    {"tierra": "land/earth"},
    {"aquí": "here"},
    {"grande": "big/large"},
    {"alto": "high/tall"},
    {"tal": "such"},
    {"siga": "follow"},
    {"acto": "act"},
    {"por qué": "why"},
    {"preguntar": "to ask"},
    {"hombres": "men"},
    {"cambiar": "to change"},
    {"se fue": "he went/she went/it went/\nhe left/she left/it left"},
    {"luz": "light"},
    {"tipo": "kind/type"},
    {"fuera": "off"},
    {"necesitar": "to need"},
    {"casa": "house/home"},
    {"imagen": "picture/image"},
    {"tratar": "to try"},
    {"nosotros": "us"},
    {"de nuevo": "again"},
    {"otra vez": "again/another time"},
    {"animal": "animal"},
    {"punto": "point"},
    {"madre": "mother"},
    {"mundo": "world"},
    {"cerca": "near/close"},
    {"construir": "to build/to construct"},
    {"auto": "self"},
    {"padre": "father"},
    {"cualquier": "any/whatever/whichever"},
    {"nuevo": "new"},
    {"trabajo": "work/job"},
    {"parte": "part"},
    {"tomar": "to take/to drink"},
    {"conseguir": "to get"},
    {"hecho": "made"},
    {"vivir": "to live"},
    {"donde": "where"},
    {"después / después de": "after"},
    {"espalda": "back"},
    {"poco": "little/a little"},
    {"sólo": "only/alone/just"},
    {"ronda": "round"},
    {"hombre": "man"},
    {"años": "years"},
    {"vino": "he came/she came/it came/wine"},
    {"show": "show"},
    {"buena": "good"},
    {"dar": "to give"},
    {"nuestro": "our"},
    {"nuestros": "ours"},
    {"bajo": "under/underneath/low/short"},
    {"nombre": "name"},
    {"muy": "very"},
    {"a través de": "through"},
    {"forma": "form"},
    {"frase": "sentence"},
    {"gran": "great/big"},
    {"pensar": "to think"},
    {"decir": "to say"},
    {"ayudar": "to help"},
    {"línea": "line"},
    {"ser distinto": "to differ"},
    {"a su vez": "turn"},
    {"causa": "cause"},
    {"mucho": "much/a lot"},
    {"significa": "mean/he means/she means/it means"},
    {"antes de": "before"},
    {"movimiento": "movement/motion"},
    {"derecho": "right"},
    {"niño": "boy"},
    {"viejo": "old"},
    {"demasiado": "too much/too many"},
    {"misma": "same"},
    {"ella": "she"},
    {"todo": "all/everything/whole"},
    {"hay": "there is/there are"},
    {"cuando": "when"},
    {"hasta": "until"},
    {"usar": "to use"},
    {"camino": "way/i walk/path/road"},
    {"acerca": "about"},
    {"muchos": "many/a lot"},
    {"entonces": "then"},
    {"ellos": "them"},
    {"escribir": "to write"},
    {"haría": "i would/he would/she would"},
    {"como": "like"},
    {"así que": "so"},
    {"éstos": "these"},
    {"su": "her"},
    {"largo": "long"},
    {"cosa": "thing"},
    {"ver": "to see"},
    {"él": "him"},
    {"dos": "two"},
    {"tiene": "he has/she has/it has"},
    {"buscar": "to search/to look for"},
    {"más": "more/most"},
    {"día": "day"},
    {"podía": "I could/he could/she could"},
    {"ir": "to go"},
    {"venir": "to come"},
    {"hizo": "he did/she did/you did"},
    {"número": "number"},
    {"sonar": "sound"},
    {"no": "no"},
    {"personas": "people"},
    {"mi": "my"},
    {"sobre": "over/about"},
    {"saber": "to know"},
    {"agua": "water"},
    {"llamada": "call"},
    {"primero": "first"},
    {"puede": "he can/she can/it can/he is able/she is able/it is able"},
    {"abajo": "down"},
    {"lado": "side"},
    {"he estado": "I have been/I've been"},
    {"ahora": "now"},
    {"ahorita": "right now/now"},
    {"encontrar": "to find"},
    {"cabeza": "head"},
    {"propio": "own"},
    {"página": "page"},
    {"debería": "I should/He should/She should"},
    {"país": "country"},
    {"he encontrado": "I have found/I've found"},
    {"respuesta": "answer"},
    {"escuela": "school"},
    {"crecer": "to grow"},
    {"estudio": "study/I study"},
    {"todavía": "still"},
    {"aprender": "to learn"},
    {"planta": "plant"},
    {"cubierta": "cover"},
    {"alimentos": "food"},
    {"sol": "sun"},
    {"cuatro": "four"},
    {"entre": "between"},
    {"estado": "state"},
    {"mantener": "to keep"},
    {"ojo": "eye"},
    {"nunca": "never"},
    {"último": "last"},
    {"dejar": "to let"},
    {"pensado": "I have thought/I've thought"},
    {"ciudad": "city"},
    {"árbol": "tree"},
    {"cruzar": "to cross"},
    {"granja": "farm"},
    {"duro": "hard"},
    {"inicio": "start/I start/I begin"},
    {"podría": "I might/he might/she might"},
    {"historia": "story/history"},
    {"sierra": "saw/mountains"},
    {"mar": "sea"},
    {"dibujar": "to draw"},
    {"izquierda": "left"},
    {"tarde": "late/afternoon"},
    {"correr": "to run"},
    {"mientras": "while"},
    {"cerrar": "to close"},
    {"noche": "night"},
    {"reales": "real"},
    {"vida": "life"},
    {"pocos": "a few/few"},
    {"norte": "north"},
    {"libro": "book"},
    {"llevar": "to carry/to take/to wear"},
    {"tomó": "he took/he drank/she took/she drank/it took/it drank"},
    {"ciencia": "science"},
    {"comer": "to eat"},
    {"habitación": "room/bedroom"},
    {"amigo": "friend"},
    {"comenzó": "he began/he commenced/she began\n"
        "/she commenced/it began/it commenced"},
    {"peces": "fish/fishes"},
    {"montaña": "mountain"},
    {"detener": "to stop"},
    {"una vez": "once"},
    {"base de": "base"},
    {"escuchar": "to hear"},
    {"caballo": "horse"},
    {"cortada": "cut"},
    {"seguro": "sure"},
    {"ver": "to watch"},
    {"colores": "colors"},
    {"cara": "face"},
    {"madera": "wood"},
    {"principal": "main/principal"},
    {"abierta": "open"},
    {"parecer": "to seem"},
    {"juntos": "together"},
    {"próximo": "next"},
    {"blanco": "white"},
    {"niños": "children"},
    {"comenzar": "to begin"},
    {"conseguido": "got"},
    {"caminar": "to walk"},
    {"ejemplo": "example"},
    {"aliviar": "to ease"},
    {"papel": "paper"},
    {"grupo": "group"},
    {"siempre": "always"},
    {"música": "music"},
    {"los": "the"},
    {"ambos": "both"},
    {"marca": "mark"},
    {"menudo": "small/slight"},
    {"carta": "letter"},
    {"hasta": "until"},
    {"milla": "mile"},
    {"río": "river"},
    {"coche": "car"},
    {"pies": "feet"},
    {"cuidado": "care"},
    {"segundo": "second"},
    {"suficiente": "enough"},
    {"llano": "plain/flat"},
    {"chica": "girl"},
    {"habitual": "usual"},
    {"joven": "young"},
    {"listo": "ready"},
    {"por encima de": "over/above"},
    {"rojo": "red"},
    {"lista": "list"},
    {"aunque": "although/though"},
    {"sentir": "to feel"},
    {"charlar": "to talk"},
    {"pájaro": "bird"},
    {"pronto": "soon"},
    {"cuerpo": "body"},
    {"perro": "dog"},
    {"familia": "family"},
    {"directa": "direct"},
    {"plantear": "to pose"},
    {"dejar": "to leave"},
    {"canción": "song"},
    {"medir": "to measure"},
    {"puerta": "door"},
    {"producto": "product"},
    {"negro": "black"},
    {"corto": "short"},
    {"numeral": "numeral"},
    {"clase": "class"},
    {"viento": "wind"},
    {"pregunta": "question"},
    {"suceder": "to happen"},
    {"completo": "complete"},
    {"buque": "ship"},
    {"zona": "area/zone"},
    {"medio": "half"},
    {"roca": "rock"},
    {"orden": "order"},
    {"fuego": "fire"},
    {"sur": "south"},
    {"problema": "problem"},
    {"pieza": "piece"},
    {"he dicho": "I have told/I've told"},
    {"sabía": "I knew/he knew/she knew"},
    {"pasar": "to pass"},
    {"cima": "top/summit/peak"},
    {"rey": "king"},
    {"calle": "street"},
    {"pulgada": "inch"},
    {"multiplicar": "to multiply"},
    {"nada": "nothing/anything"},
    {"curso": "course"},
    {"quedarse": "to stay"},
    {"rueda": "wheel"},
    {"completo": "full/total/entire"},
    {"fuerza": "force/strength/he forces/she forces"},
    {"azul": "blue"},
    {"objeto": "object"},
    {"decidir": "to decide"},
    {"superficie": "surface"},
    {"profunda": "deep/profound"},
    {"luna": "moon"},
    {"isla": "island"},
    {"pie": "foot"},
]
