"""
A dictionary of spanish - english translations
which are deemed to be at a hard level of difficulty"""
hard_words = [
    {"ha empujado": "he has pushed/she has pushed/it has pushed"},
    {"siete": "seven"},
    {"párrafo": "paragraph"},
    {"tercero": "third"},
    {"deber": "to owe/should"},
    {"deberia": "i should"},
    {"en espera": "on hold"},
    {"pelo": "hair"},
    {"describir": "to describe"},
    {"describo": "i describe"},
    {"describí": "i described"},
    {"describiste": "you described"},
    {"cocinero": "chef/cook"},
    {"piso": "floor"},
    {"ya sea": "either"},
    {"resultado": "result"},
    {"quemar": "to burn"},
    {"quemó": "he burned/she burned/it burned"},
    {"quemé": "i burned"},
    {"colina": "hill"},
    {"seguro": "safe/sure"},
    {"gato": "cat"},
    {"perro": "dog"},
    {"siglo": "century"},
    {"considerar": "to consider"},
    {"consideré": "I considered"},
    {"considerando": "considering"},
    {"he considerado": "I have considered"},
    {"tipo": "type"},
    {"ley": "law"},
    {"rato": "while/a while/bit/a bit"},
    {"costa": "coast"},
    {"copia": "copy/imitation"},
    {"copiadora": "photocopier"},
    {"frase": "sentence/phrase"},
    {"silencio": "silence"},
    {"altura": "height"},
    {"arena": "sand"},
    {"suelo": "soil"},
    {"rollo": "roll"},
    {"temperatura": "temperature"},
    {"dedo": "finger"},
    {"industria": "industry"},
    {"valor": "valor/value"},
    {"lucha": "fight/struggle"},
    {"guerra": "war"},
    {"mentira": "lie"},
    {"batir": "to beat"},
    {"batiré": "i will beat"},
    {"batirás": "you will beat"},
    {"he batido": "I have beaten beat"},
    {"excitar": "to excite"},
    {"natural": "natural"},
    {"vista": "view"},
    {"capital": "capital"},
    {"ciudad capital": "capital city"},
    {"no lo haré": "i won’t do it/i will not do it"},
    {"lo haré": "i will do it"},
    {"silla": "chair"},
    {"mesa": "table"},
    {"peligroso": "danger"},
    {"fruta": "fruit"},
    {"rico": "rich/delicious"},
    {"de espesor": "thickness/depth"},
    {"soldado": "soldier"},
    {"proceso": "process/trial"},
    {"operar": "to operate/to operate on"},
    {"operó": "she operated on/he operated on/it operated on"},
    {"operé": "I operated on"},
    {"practica": "practice"},
    {"separada": "separated"},
    {"separar": "to separate"},
    {"separé": "I separated"},
    {"se separaron": "they separated/they split up"},
    {"difícil": "difficult"},
    {"médico": "doctor"},
    {"por favor": "please"},
    {"proteger": "to protect"},
    {"protejo": "i protect"},
    {"protegió": "she protected/he protected/it protected"},
    {"mediodía": "noon/midday/mid-day"},
    {"moderno": "modern"},
    {"elemento": "element"},
    {"golpear": "to hit"},
    {"golpeé": "I hit/(past tense)"},
    {"golpeo": "to hit/(present tense)"},
    {"estudiante": "student"},
    {"esquina": "corner"},
    {"partido": "match/game"},
    {"suministro": "supply"},
    {"cuya": "whose"},
    {"localizar": "to locate"},
    {"localizamos": "we located/we locate"},
    {"localizaron": "they located"},
    {"anillo": "ring"},
    {"carácter": "character"},
    {"insecto": "insect"},
    {"capturado": "caught"},
    {"período": "period"},
    {"indicar": "to indicate"},
    {"indiqué": "i indicated"},
    {"indicó": "he indicated/she indicated/it indicated"},
    {"Radio": "radio"},
    {"habló": "he spoke/she spoke/it spoke"},
    {"hablé": "i spoke"},
    {"átomo": "atom"},
    {"humano": "human/human being"},
    {"efecto": "effect"},
    {"eléctrico": "electric"},
    {"esperar": "to wait/to wait for/to hope"},
    {"espero": "i hope/i wait/i wait for"},
    {"esperé": "i waited/i waited for/i hoped"},
    {"hueso": "bone"},
    {"ferrocarril": "ailroad/railway"},
    {"imaginar": "to imagine"},
    {"imagino": "i imagine"},
    {"imaginé": "i imagined"},
    {"imaginó": "he imagined/she imagined/it imagined"},
    {"he imaginado": "i have imagined"},
    {"proporcionar": "to provide"},
    {"proporcionaron": "they provided"},
    {"he proporcionado": "i have provided"},
    {"han proporcionado": "they have provided"},
    {"proporcionamos": "we provide/we provided"},
    {"acuerdo": "agreement/i agree"},
    {"acordar": "to agree"},
    {"por lo tanto": "therefore/thus/hence"},
    {"suave": "gentle/soft/smooth"},
    {"mujer": "woman"},
    {"capitán": "captain"},
    {"adivinar": "to guess"},
    {"necesario": "necessary"},
    {"agudo": "sharp/acute"},
    {"ala": "wing"},
    {"ave": "bird"},
    {"pajaro": "bird"},
    {"crear": "to create"},
    {"he creado": "i have created"},
    {"creé": "i created"},
    {"creó": "he created/she created/it created"},
    {"crear": "to create"},
    {"vecino": "neighbor"},
    {"lavado": "washed"},
    {"bate": "bat"},
    {"más bien": "rather"},
    {"multitud": "crowd"},
    {"maíz": "corn"},
    {"comparar": "to compare"},
    {"compararon": "they compared"},
    {"comparamos": "we compared/we compare"},
    {"comparando": "comparing"},
    {"poema": "poem"},
    {"cadena": "chain"},
    {"campana": "bell"},
    {"depende de": "it depends on"},
    {"carne": "meat/flesh"},
    {"frotar": "to rub/to scrub"},
    {"tubo": "tube/pipe"},
    {"famoso": "famous"},
    {"dólar": "dollar"},
    {"corriente": "current/common"},
    {"miedo": "fear"},
    {"vista": "view/sight"},
    {"delgado": "thin"},
    {"triángulo": "triangle"},
    {"planeta": "planet"},
    {"prisa": "hurry/rush"},
    {"jefe": "boss"},
    {"colonia": "colony"},
    {"reloj": "clock/watch"},
    {"mina": "mine/(e.g. coal mine)"},
    {"entrar": "to enter"},
    {"entré": "i entered"},
    {"entraron": "they entered"},
    {"entramos": "we entered/we enter"},
    {"importante": "important"},
    {"búsqueda": "search"},
    {"enviar": "to send"},
    {"envié": "i sent"},
    {"envió": "he sent/she sent/it sent"},
    {"amarillo": "yellow"},
    {"pistola": "pistol"},
    {"permitir": "to permit/to allow"},
    {"muerto": "dead"},
    {"desierto": "desert"},
    {"traje": "suit"},
    {"actual": "current/present/up-to-date/up to date"},
    {"rosa": "rose"},
    {"llegué": "i arrived"},
    {"llego": "i arrive"},
    {"llegó": "he arrived/she arrived/it arrived"},
    {"master": "master"},
    {"pista": "road"},
    {"padre": "parent/father"},
    {"padres": "parents"},
    {"orilla": "shore"},
    {"división": "division"},
    {"hoja": "leaf/sheet"},
    {"sustancia": "substance"},
    {"conectar": "to connect"},
    {"conecto": "i connect"},
    {"conecté": "i connected"},
    {"mensaje": "message"},
    {"pasar": "to spend/to pass/to happen"},
    {"acorde": "chord/in accordance with"},
    {"grasa": "fat/grease"},
    {"contento": "glad/happy/content"},
    {"original": "original"},
    {"cuota": "fee"},
    {"estación": "station/season"},
    {"papá": "dad"},
    {"papa": "potato"},
    {"pan": "bread"},
    {"adecuada": "appropriate/suitable"},
    {"aprensivo": "apprehensive"},
    {"barra": "bar"},
    {"oferta": "offer"},
    {"segmento": "segment"},
    {"esclavo": "slave"},
    {"pato": "duck"},
    {"instantánea": "snapshot/snap shot/snap-shot"},
    {"mercado": "market"},
    {"grado": "degree/grade"},
    {"poblar": "to populate"},
    {"polluelo": "chick"},
    {"pollo": "chicken"},
    {"querido": "dear/honey/baby/darling"},
    {"enemigo": "enemy"},
    {"amigo": "friend"},
    {"responder": "to reply"},
    {"bebida": "drink"},
    {"apoyo": "support/i support"},
    {"discurso": "speech"},
    {"naturaleza": "nature"},
    {"alcance": "reach/scope/i reach"},
    {"vapor": "steam/vapor/vapour"},
    {"líquido": "liquid"},
    {"log": "log"},
    {"significado": "meaning"},
    {"dientes": "teeth"},
    {"concha": "shell"},
    {"cuello": "neck"},
    {"oxígeno": "oxygen"},
    {"azúcar": "sugar"},
    {"muerte": "death"},
    {"bastante": "quite/quite a lot/a fair amount/plenty/enough"},
    {"habilidad": "ability/skill"},
    {"mujeres": "women"},
    {"temporada": "season/period of time"},
    {"solución": "solution"},
    {"imán": "magnet"},
    {"plata": "silver"},
    {"gracias": "thank you"},
    {"rama": "branch"},
    {"sufijo": "suffix"},
    {"especialmente": "especially"},
    {"higo": "fig"},
    {"enorme": "enormous/huge"},
    {"hermana": "sister"},
    {"acero": "steel"},
    {"discutir": "to argue/to discuss"},
    {"discutieron": "they argued/they discussed"},
    {"discutí": "i argued/i discussed"},
    {"discutió": "he argued/she argued/it argued/\n"
        "she discussed/he discussed/it discussed"},
    {"adelante": "forward"},
    {"similar": "similar"},
    {"guiar": "to guide"},
    {"experiencia": "experience"},
    {"puntuación": "punctuation/grade"},
    {"manzana": "apple"},
    {"comprado": "bought"},
    {"he llevado": "I have taken/I have worn/I have carried"},
    {"abrigo": "coat"},
    {"masa": "mass"},
    {"tarjeta": "card"},
    {"banda": "band"},
    {"cuerda": "rope"},
    {"deslizamiento": "slip/slipping/slide/sliding"},
    {"huellas dactilares": "fingerprints/finger prints"},
    {"ganar": "to win"},
    {"soñar": "to dream"},
    {"noche": "night"},
    {"condición": "condition"},
    {"herramienta": "tool"},
    {"total": "complete/total"},
    {"básico": "basic"},
    {"olor": "smell/odor"},
    {"valle": "valley"},
    {"ni": "nor"},
    {"doble": "double"},
    {"asiento": "seat"},
    {"continuar": "to continue"},
    {"bloque": "block"},
    {"tabla": "board"},
    {"tabla de cortar": "cutting board"},
    {"sombrero": "hat"},
    {"gora": "cap"},
    {"vender": "to sell"},
    {"venderé": "i will sell"},
    {"vendí": "i sold"},
    {"vendieron": "they sold"},
    {"he vendido": "i have sold"},
    {"éxito": "success"},
    {"empresa": "company"},
    {"restar": "to subtract"},
    {"evento": "event"},
    {"particular": "particular"},
    {"nadar": "to swim"},
    {"plazo": "term"},
    {"opuesto": "opposite"},
    {"esposa": "wife"},
    {"esposo": "husband"},
    {"zapato": "shoe"},
    {"hombro": "shoulder"},
    {"propagación": "propagation/spreading/spread"},
    {"organizar": "to organise/to organize"},
    {"campamento": "camp"},
    {"inventar": "to invent"},
    {"algodón": "cotton"},
    {"nacer": "to be born"},
    {"nací": "i was born"},
    {"determinar": "to determine"},
    {"nueve": "nine"},
    {"camión": "truck"},
    {"ruido": "noise"},
    {"nivel": "level"},
    {"oportunidad": "opportunity"},
    {"tramo": "stretch"},
    {"lanzar": "to throw/to launch"},
    {"brillo": "brightness/shine"},
    {"propiedad": "property"},
    {"columna": "column"},
    {"molécula": "molecule"},
    {"seleccionar": "to select"},
    {"mal": "bad"},
    {"gris": "gray"},
    {"amplio": "wide"},
    {"preparar": "to prepare"},
    {"sal": "salt"},
    {"nariz": "nose"},
    {"plural": "plural"},
    {"cólera": "anger"},
    {"reclamación": "claim"},
    {"inente": "continent"}
]
