"""
A dictionary of spanish - english translations
which are deemed to be at a medium level of difficulty"""
medium_words = [
    {"sistema": "system"},
    {"ocupado": "busy"},
    {"prueba": "test/he tries/she tries/try"},
    {"registro": "record"},
    {"barco": "boat"},
    {"común": "common"},
    {"oro": "gold"},
    {"posible": "possible"},
    {"plano": "plane/flat"},
    {"lugar": "place"},
    {"seco": "dry"},
    {"maravilla": "wonder/he amazes/she amazes/it amazes"},
    {"risa": "laugh"},
    {"mil": "thousand"},
    {"hace diez años": "10 years ago"},
    {"corrió": "he ran/she ran/it ran"},
    {"comprobar": "to check"},
    {"juego": "game"},
    {"forma": "shape/form/way"},
    {"equiparar": "to equate"},
    {"caliente": "hot"},
    {"señorita": "miss"},
    {"traído": "brought/worn/worn out"},
    {"calor": "heat"},
    {"nieve": "snow"},
    {"neumáticos": "tire"},
    {"traer": "to bring"},
    {"sí": "yes/if"},
    {"distante": "distant"},
    {"llenar": "to fill"},
    {"al este": "to the east"},
    {"pintar": "to paint"},
    {"idioma": "language"},
    {"entre": "among/between"},
    {"unidad": "unit"},
    {"potencia": "potential/power"},
    {"ciudad": "city"},
    {"fina": "fine"},
    {"cierto": "certain/sure/of course"},
    {"volar": "to fly"},
    {"caer": "to fall"},
    {"conducir": "to lead"},
    {"grito": "shout/scream/I scream/I shout"},
    {"oscuro": "dark"},
    {"máquina": "machine"},
    {"nota": "note"},
    {"espere": "wait"},
    {"plan de": "plan"},
    {"figura": "figure/model"},
    {"estrella": "star"},
    {"caja": "box"},
    {"sustantivo": "noun"},
    {"campo": "field"},
    {"resto": "rest"},
    {"correcta": "correct"},
    {"capaz": "able/capable"},
    {"libra": "pound/he frees/she frees/it frees"},
    {"he hecho": "I have done"},
    {"has hecho": "You have done"},
    {"ha hecho": "He has done/She has done"},
    {"belleza": "beauty"},
    {"unidad": "unity/unit"},
    {"destacado": "outstanding/distinguished"},
    {"contener": "to contain"},
    {"delante": "in front/ahead"},
    {"enseñar": "to teach"},
    {"semana": "week"},
    {"último": "final/last/ultimate"},
    {"dio": "he gave/it gave/she gave"},
    {"verde": "green"},
    {"rápido": "quick/fast/rapid"},
    {"desarrollar": "to develop"},
    {"océano": "ocean"},
    {"caliente": "warm/hot"},
    {"minuto": "minute"},
    {"fuerte": "strong"},
    {"especial": "special"},
    {"mente": "mind"},
    {"detrás": "behind"},
    {"claro": "clear"},
    {"cola": "tail"},
    {"espacio": "space"},
    {"oído": "heard"},
    {"mejor": "best"},
    {"hora": "hour/time"},
    {"mejor": "better"},
    {"mejorar": "to improve"},
    {"verdadero": "true/real"},
    {"durante": "during"},
    {"cien": "hundred"},
    {"cinco": "five"},
    {"recordar": "to remember"},
    {"paso": "step"},
    {"temprana": "early"},
    {"mantenga": "hold"},
    {"al oeste": "to the west"},
    {"suelo": "ground/floor/land/soil"},
    {"interés": "interest"},
    {"llegar": "to arrive/to reach"},
    {"verbo": "verb"},
    {"cantar": "to sing"},
    {"escuchar": "to listen"},
    {"seis": "six"},
    {"mesa": "table"},
    {"viaje": "trip/journey"},
    {"menos": "less"},
    {"mañana": "morning/tomorrow"},
    {"diez": "ten"},
    {"sencilla": "simple"},
    {"varios": "several/various"},
    {"vocal": "vocal"},
    {"hacia": "toward/towards/I was doing/She was doing/He was doing"},
    {"guerra": "war"},
    {"sentarse": "to sit"},
    {"contra": "against"},
    {"patrón": "pattern/boss"},
    {"lento": "slow"},
    {"centro": "center"},
    {"amar": "to love"},
    {"persona": "person"},
    {"dinero": "money"},
    {"servir": "to serve"},
    {"aparecerá": "to appear"},
    {"carretera": "road"},
    {"mapa": "map"},
    {"lluvia": "rain"},
    {"regla": "rule"},
    {"gobernar": "to govern"},
    {"halar": "to pull"},
    {"frío": "cold"},
    {"aviso": "notice/warning"},
    {"voz": "voice"},
    {"energía": "energy"},
    {"caza": "hunt/he hunts/she hunts/it hunts"},
    {"probable": "probable"},
    {"cama": "bed"},
    {"hermano": "brother"},
    {"huevo": "egg"},
    {"paseo": "ride/drive"},
    {"celular": "cellphone/cell phone/mobile/mobile phone"},
    {"creer": "to believe"},
    {"quizás": "perhaps/maybe"},
    {"recoger": "to pick up/to gather/to collect"},
    {"repentina": "sudden"},
    {"de repente": "sudden/suddenly"},
    {"contar": "to count/to tell"},
    {"plaza": "square/plaza"},
    {"razón": "reason"},
    {"longitud": "length"},
    {"representar": "to represent"},
    {"arte": "art"},
    {"sujeto": "subject"},
    {"región": "region"},
    {"tamaño": "size"},
    {"variar": "to vary/to alter"},
    {"resolver": "to settle/to resolve"},
    {"hablar": "to speak"},
    {"peso": "weight"},
    {"general": "general"},
    {"hielo": "ice"},
    {"materia": "matter"},
    {"círculo": "circle"},
    {"par": "pair"},
    {"incluir": "to include"},
    {"brecha": "breach/gash/opening"},
    {"sílaba": "syllable"},
    {"sentido": "sense/meaning"},
    {"bola": "ball"},
    {"pelota": "ball"},
    {"aún": "yet/still"},
    {"ola": "wave"},
    {"caer": "to drop/to fall"},
    {"corazón": "heart"},
    {"En el presente": "in the present"},
    {"pesada": "heavy"},
    {"danza": "dance/He dancesSshe dances/It dances"},
    {"motor": "engine"},
    {"posición": "position"},
    {"brazo": "arm"},
    {"amplio": "wide"},
    {"vela": "sail/candle"},
    {"material": "material"},
    {"fracción": "fraction"},
    {"bosque": "forest"},
    {"carrera": "race/career"},
    {"ventana": "window"},
    {"tienda": "store"},
    {"verano": "summer"},
    {"tren": "train"},
    {"sueño": "dream"},
    {"demostrar": "to prove/to demonstrate"},
    {"solitario": "lonely"},
    {"pierna": "leg"},
    {"ejercicio": "exercise"},
    {"pared": "wall"},
    {"capturar": "to capture"},
    {"monte": "hill/mountain"},
    {"desear": "to wish/to desire/to want"},
    {"cielo": "sky"},
    {"bordo": "side"},
    {"alegría": "joy"},
    {"invierno": "winter"},
    {"satélite": "satellite"},
    {"escrito": "written"},
    {"salvaje": "wild"},
    {"instrumento": "instrument"},
    {"guardar": "to put away/to save/to keep"},
    {"vidrio": "glass"},
    {"hierba": "grass/herb"},
    {"vaca": "cow"},
    {"trabajo": "job/I work"},
    {"borde": "edge/rude"},
    {"signo": "sign"},
    {"visita": "visit"},
    {"pasado": "past"},
    {"diversión": "fun"},
    {"brillante": "bright"},
    {"gasolina": "gas"},
    {"tiempo": "weather/time"},
    {"mes": "month"},
    {"millon": "million"},
    {"soportar": "to stand for/to put up with/to support"},
    {"acabado": "finished"},
    {"feliz": "happy"},
    {"esperanza": "hope"},
    {"flor": "flower"},
    {"vestir": "to wear/to dress"},
    {"extraño": "strange"},
    {"comercio": "trade/I trade"},
    {"melodía": "melody"},
    {"viaje": "trip"},
    {"oficina": "office"},
    {"recibir": "To receive"},
    {"fila": "row/line"},
    {"boca": "mouth"},
    {"exacto": "exact"},
    {"símbolo": "symbol"},
    {"morir": "to die"},
    {"menos": "The least/less/fewer"},
    {"problema": "problem"},
    {"excepto": "except"},
    {"escribió": "wrote"},
    {"semilla": "seed"},
    {"tono": "tone"},
    {"unirse": "To join"},
    {"sugerir": "To suggest"},
    {"limpiar": "To clean"},
    {"limpia": "He cleans/She cleans/It cleans/clean"},
    {"rotura": "break/fracture"},
    {"dama": "lady"},
    {"patio": "yard"},
    {"aumentando": "increasing/raising"},
    {"mal": "bad"},
    {"golpe": "hit"},
    {"aceite": "oil"},
    {"sangre": "blood"},
    {"tocar": "To touch"},
    {"crecer": "to grow"},
    {"ciento": "cent/hundred/a hundred/one hundred"},
    {"mezclar": "to mix"},
    {"equipo": "team"},
    {"alambre": "wire"},
    {"costo": "cost"},
    {"perdido": "lost"},
    {"marrón": "brown"},
    {"jardín": "garden"},
    {"igual": "equal/same"},
    {"elegir": "To choose"},
    {"cayó": "he fell/she fell/it fell"},
    {"encajar": "To fit"},
    {"fluir": "To flow"},
    {"justo": "fair"},
    {"banco": "bank"},
    {"control": "control"},
    {"decimal": "decimal"},
    {"oído": "ear"},
    {"demás": "other/the rest"},
    {"bastante": "quite"},
    {"rompió": "he broke/she broke/it broke"},
    {"romper": "to break"},
    {"he roto": "i have broken"},
    {"has roto": "you have broken"},
    {"caso": "case"},
    {"medio": "middle"},
    {"matar": "to kill"},
    {"mató": "he killed/she killed/it killed"},
    {"hijo": "son"},
    {"lago": "lake"},
    {"momento": "moment"},
    {"escalar": "to climb/to scale"},
    {"fuerte": "strong/sturdy"},
    {"primavera": "spring"},
    {"observar": "to observe"},
    {"niño": "child"},
    {"recta": "straight/straight line"},
    {"consonante": "consonant"},
    {"nación": "nation"},
    {"diccionario": "dictionary"},
    {"leche": "milk"},
    {"velocidad": "speed/velocity"},
    {"método": "method"},
    {"órgano": "organ"},
    {"pagar": "to pay"},
    {"edad": "age"},
    {"sección": "section"},
    {"vestido": "dress"},
    {"nube": "cloud"},
    {"sorpresa": "surprise"},
    {"tranquila": "quiet"},
    {"piedra": "stone"},
    {"pequeño": "small"},
    {"ascenso": "promotion/ascent"},
    {"fresco": "fresh"},
    {"diseño": "design"},
    {"pobre": "poor"},
    {"mucho": "lot/a lot"},
    {"experimento": "experiment"},
    {"inferior": "bottom/lower/inferior"},
    {"clave": "key/password/code"},
    {"hierro": "iron"},
    {"solo": "only/alone/single"},
    {"palillo": "toothpick"},
    {"veinte": "twenty"},
    {"piel": "skin"},
    {"sonrisa": "smile"},
    {"pliegue": "crease"},
    {"arruga": "crease/wrinkle"},
    {"agujero": "hole"},
    {"saltar": "to jump"},
    {"salté": "i jumped"},
    {"he saltado": "i have jumped"},
    {"saltaste": "you jumped"},
    {"bebé": "baby"},
    {"ocho": "eight"},
    {"pueblo": "village"},
    {"raíz": "root"},
    {"comprar": "to buy"},
    {"compro": "i buy"},
    {"compré": "i bought"},
    {"has comprado": "you have bought"},
    {"aumentar": "to increase/to raise"},
    {"metal": "metal"},
    {"si": "whether/yes/if"},
    {"empujar": "to push"},
    {"empujé": "i pushed"},
]
